<pre class='metadata'>
Title: Resource Timing
Shortname: resource-timing
Status: ED
Group: webperf
URL: https://w3c.github.io/resource-timing/
TR: https://www.w3.org/TR/resource-timing/
Editor: Yoav Weiss, Shopify https://shopify.com/, https://blog.yoav.ws/, w3cid 58673
Editor: Noam Rosenthal, Google https://google.com/, nrosenthal@chromium.org, w3cid 121539
Former Editor: Ilya Grigorik, Google https://google.com/, https://www.igvita.com/, w3cid 56102
Former Editor: Todd Reifsteck, Microsoft Corp., toddreif@microsoft.com, w3cid 76565
Former Editor: Arvind Jain, Google Inc., arvind@google.com, w3cid 45188
Former Editor: Jatinder Mann, Microsoft Corp., jmann@microsoft.com, w3cid 44357
Former Editor: Zhiheng Wang, Google Inc., w3cid 43685
Former Editor: Anderson Quach, Microsoft Corp., w3cid 45288
Repository: w3c/resource-timing
Mailing List: public-web-perf@w3.org
Mailing List Archives: https://lists.w3.org/Archives/Public/public-web-perf/
Include Can I Use Panels: yes
Can I Use URL: https://caniuse.com/resource-timing
Abstract: This specification defines an interface for web applications to access the complete timing information for resources in a document.
Level: none
Complain About: accidental-2119 yes
Markup Shorthands: markdown no
</pre>

<pre class=link-defaults>
spec:html; type:element; text:script
spec:html; type:element; text:link
spec:html; type:element; text:body
spec:html; type:element; text:audio
spec:html; type:element; text:a
spec:html; type:element-attr; for:a; text:ping
spec:fetch; type:dfn; for:/; text:request
spec:fetch; type:dfn; for:/; text:response
spec:service-workers; type:dfn; for:/; text:service worker
spec:html; type:dfn; for:/; text:global object
</pre>

<pre class=anchors>
urlPrefix: https://www.w3.org/TR/performance-timeline/; spec: PERFORMANCE-TIMELINE-2; type: dfn
    text: Performance Timeline; url: #performance-timeline
    text: performance entry buffer; url: #dfn-performance-entry-buffer
    text: Queue a PerformanceEntry; url: #dfn-queue-a-performanceentry
    text: initialize a PerformanceEntry; url: #dfn-initialize-a-performanceentry
    text: performance timeline task source; url: #dfn-performance-timeline-task-source
urlPrefix: https://fetch.spec.whatwg.org/; spec: FETCH; type: dfn
    text: Recording connection timing info; url: #record-connection-timing-info
</pre>

<pre class=biblio>
{
  "INCREMENTAL_FONT_TRANSFER": {
    "title": "Incremental Font Transfer",
    "href": "https://www.w3.org/TR/IFT/"
  },
  "EARLY_HINTS": {
    "title": "Early hints",
    "href": "https://httpwg.org/specs/rfc8297.html"
  }
}
</pre>

<section class='informative'>
  <h2 id="introduction">
    Introduction
  </h2>
  <p>
    User latency is an important quality benchmark for Web Applications.
    While JavaScript-based mechanisms can provide comprehensive
    instrumentation for user latency measurements within an application, in
    many cases, they are unable to provide a complete end-to-end latency
    picture. This document introduces the {{PerformanceResourceTiming}}
    interface to allow JavaScript mechanisms to collect complete timing
    information related to resources on a document. Navigation Timing 2
    [[NAVIGATION-TIMING-2]] extends this specification to provide
    additional timing information associated with a navigation.
  </p>
  <p>
    For example, the following JavaScript shows a simple attempt to measure
    the time it takes to fetch a resource:
  </p>
  <pre class='example' highlight='html'>
    &lt;!doctype html&gt;
    &lt;html&gt;
      &lt;head&gt;
      &lt;/head&gt;
      &lt;body onload="loadResources()"&gt;
        &lt;script&gt;
            function loadResources()
            {
              var start = new Date().getTime();
              var image1 = new Image();
              var resourceTiming = function() {
                  var now = new Date().getTime();
                  var latency = now - start;
                  alert("End to end resource fetch: " + latency);
              };

              image1.onload = resourceTiming;
              image1.src = 'https://www.w3.org/Icons/w3c_main.png';
            }
        &lt;/script&gt;
        &lt;img src="https://www.w3.org/Icons/w3c_home.png"&gt;
      &lt;/body&gt;
    &lt;/html&gt;
    </pre>
  <p>
    Though this script can measure the time it takes to fetch a resource,
    it cannot break down the time spent in various phases. Further, the
    script cannot easily measure the time it takes to fetch resources
    described in markup.
  </p>
  <p>
    To address the need for complete information on user experience, this
    document introduces the {{PerformanceResourceTiming}} interface.
    This interface allows JavaScript mechanisms to provide complete
    client-side latency measurements within applications. With this
    interface, the previous example can be modified to measure a user's
    perceived load time of a resource.
  </p>
  <p>
    The following script calculates the amount of time it takes to fetch
    every resource in the page, even those defined in markup. This example
    assumes that this page is hosted on https://www.w3.org. One could
    further measure the amount of time it takes in every phase of fetching
    a resource with the {{PerformanceResourceTiming}} interface.
  </p>
  <pre class='example' highlight='html'>
    &lt;!doctype html&gt;
    &lt;html&gt;
      &lt;head&gt;
      &lt;/head&gt;
      &lt;body onload="loadResources()"&gt;
        &lt;script&gt;
          function loadResources()
          {
              var image1 = new Image();
              image1.onload = resourceTiming;
              image1.src = 'https://www.w3.org/Icons/w3c_main.png';
          }

          function resourceTiming()
          {
              var resourceList = window.performance.getEntriesByType("resource");
              for (i = 0; i &lt; resourceList.length; i++)
              {
                  if (resourceList[i].initiatorType == "img")
                  {
                    alert("End to end resource fetch: " + (resourceList[i].responseEnd - resourceList[i].startTime));
                  }
              }
          }
        &lt;/script&gt;
        &lt;img id="image0" src="https://www.w3.org/Icons/w3c_home.png"&gt;
      &lt;/body&gt;
    &lt;/html&gt;
    </pre>
</section>
<section>
  <h2 id="terminology">
    Terminology
  </h2>
  <p>
    The construction "a <code>Foo</code> object", where <code>Foo</code> is
    actually an interface, is sometimes used instead of the more accurate
    "an object implementing the interface <code>Foo</code>.
  </p>
  <p>
    Throughout this work, all time values are measured in milliseconds
    since the start of navigation of the document [[HR-TIME]]. For example,
    the <a href="https://www.w3.org/TR/navigation-timing-2/#performanceentry">start of
    navigation of the document</a> occurs at time 0.
  </p>
  <p class='note'>
    This definition of time is based on the High Resolution Time
    specification [[HR-TIME]] and is different from the definition of time
    used in the Navigation Timing specification [[NAVIGATION-TIMING-2]],
    where time is measured in milliseconds since midnight of January 1,
    1970 (UTC).
  </p>
</section>
<section>
  <h2 id="sec-resource-timing">
    Resource Timing
  </h2>
  <section class='informative'>
    <h3 id="sec-resource-timing-intro">
      Introduction
    </h3>
    <p>
      The {{PerformanceResourceTiming}} interface facilitates timing
      measurement of [=fetch|fetched=] [=http(s) scheme|http(s)=]
      resources. For example, this interface is available for
      {{XMLHttpRequest}} objects [[XHR]], HTML elements [[HTML]] such as
      <{iframe}>, <{img}>, <{script}>, <{object}>, <{embed}> and <{link}>
      with the link type of <a href="https://html.spec.whatwg.org/multipage/semantics.html#link-type-stylesheet">stylesheet</a>, SVG elements [[SVG11]]
      such as <a href="https://www.w3.org/TR/SVG11/struct.html#SVGElement">svg</a>, and
      {{EventSource}}.
    </p>
  </section>
  <section>
    <h3 id="resources-included-in-the-performanceresourcetiming-interface">
      Resources Included in the {{PerformanceResourceTiming}} Interface
    </h3>
    <p>
      This section is non-normative.
    </p>
    <p>
      Resource [=Request=]s [=fetch=]ed by a non-null [=request/client=]
      are included as {{PerformanceResourceTiming}} objects in the
      [=request/client=]'s [=environment settings object/global object=]'s
      <a>Performance Timeline</a>, unless excluded from the timeline as
      part of the [=fetch|fetching process=]. Resources that are retrieved
      from HTTP cache are included as {{PerformanceResourceTiming}}
      objects in the <a>Performance Timeline</a>. Resources for which the
      [=fetch=] was initiated, but was later aborted (e.g. due to a network
      error) are included as {{PerformanceResourceTiming}} objects in
      the <a>Performance Timeline</a>, with their start and end timing.
    </p>
    <p>
      Examples:
    </p>
    <ul>
      <li>If the same canonical URL is used as the <code>src</code>
      attribute of two HTML <code>IMG</code> elements, the [=fetch=] of the
      resource initiated by the first HTML <code>IMG</code> element would
      be included as a {{PerformanceResourceTiming}} object in the
      <a>Performance Timeline</a>. The user agent might not re-request the
      URL for the second HTML <code>IMG</code> element, instead using the
      existing download it initiated for the first HTML <code>IMG</code>
      element. In this case, the [=fetch=] of the resource by the first
      <code>IMG</code> element would be the only occurrence in the
      <a>Performance Timeline</a>.
      </li>
      <li>If the <code>src</code> attribute of a HTML <code>IMG</code>
      element is changed via script, both the [=fetch=] of the original
      resource as well as the [=fetch=] of the new URL would be included as
      {{PerformanceResourceTiming}} objects in the <a>Performance
      Timeline</a>.
      </li>
      <li>If an HTML <code>IFRAME</code> element is added via markup
      without specifying a <code>src</code> attribute, the user agent may
      load the <code>about:blank</code> document for the
      <code>IFRAME</code>. If at a later time the <code>src</code>
      attribute is changed dynamically via script, the user agent may
      [=fetch=] the new URL resource for the <code>IFRAME</code>. In this
      case, only the [=fetch=] of the new URL would be included as a
      {{PerformanceResourceTiming}} object in the <a>Performance
      Timeline</a>.
      </li>
      <li>If an <code>XMLHttpRequest</code> is generated twice for the same
      canonical URL, both [=fetches=] of the resource would be included as
      a {{PerformanceResourceTiming}} object in the <a>Performance
      Timeline</a>. This is because the [=fetch=] of the resource for the
      second <code>XMLHttpRequest</code> cannot reuse the download issued
      for the first <code>XMLHttpRequest</code>.
      </li>
      <li>If an HTML <code>IFRAME</code> element is included on the page,
      then only the resource requested by <code>IFRAME</code>
      <code>src</code> attribute is included as a
      {{PerformanceResourceTiming}} object in the <a>Performance
      Timeline</a>. Sub-resources requested by the <code>IFRAME</code>
      document will be included in the <code>IFRAME</code> document's
      <a>Performance Timeline</a> and not the parent document's
      <a>Performance Timeline</a>.
      </li>
      <li>If an HTML <code>IMG</code> element has a <code><a href=
      "https://tools.ietf.org/html/rfc2397">data: URI</a></code> as its
      source [[RFC2397]], then this resource will not be included as a
        {{PerformanceResourceTiming}} object in the <a>Performance
        Timeline</a>. {{PerformanceResourceTiming}} entries are only
        reported for [=http(s) scheme|http(s)=] resources.
      </li>
      <li>If a resource [=/fetch=] was
      aborted due to a networking error (e.g. DNS, TCP, or TLS error), then
      the fetch will be included as a {{PerformanceResourceTiming}}
      object in the <a>Performance Timeline</a> with only the <code>startTime</code>,
      <code>fetchStart</code>, <code>duration</code> and <code>responseEnd</code> set.
      </li>
      <li>If a resource [=/fetch=] is
      aborted because it failed a fetch precondition (e.g. mixed content,
      CORS restriction, CSP policy, etc), then this resource will not be
      included as a {{PerformanceResourceTiming}} object in the
      <a>Performance Timeline</a>.
      </li>
    </ul>
  </section>
  <section>
    <h3 id="sec-performanceresourcetiming">
      The PerformanceResourceTiming Interface
    </h3>
    <pre class='idl'>
      [Exposed=(Window,Worker)]
      interface PerformanceResourceTiming : PerformanceEntry {
          readonly attribute DOMString initiatorType;
          readonly attribute DOMString deliveryType;
          readonly attribute ByteString nextHopProtocol;
          readonly attribute DOMHighResTimeStamp workerStart;
          readonly attribute DOMHighResTimeStamp redirectStart;
          readonly attribute DOMHighResTimeStamp redirectEnd;
          readonly attribute DOMHighResTimeStamp fetchStart;
          readonly attribute DOMHighResTimeStamp domainLookupStart;
          readonly attribute DOMHighResTimeStamp domainLookupEnd;
          readonly attribute DOMHighResTimeStamp connectStart;
          readonly attribute DOMHighResTimeStamp connectEnd;
          readonly attribute DOMHighResTimeStamp secureConnectionStart;
          readonly attribute DOMHighResTimeStamp requestStart;
          readonly attribute DOMHighResTimeStamp finalResponseHeadersStart;
          readonly attribute DOMHighResTimeStamp firstInterimResponseStart;
          readonly attribute DOMHighResTimeStamp responseStart;
          readonly attribute DOMHighResTimeStamp responseEnd;
          readonly attribute DOMHighResTimeStamp workerRouterEvaluationStart;
          readonly attribute DOMHighResTimeStamp workerCacheLookupStart;
          readonly attribute DOMString workerMatchedRouterSource;
          readonly attribute DOMString workerFinalRouterSource;
          readonly attribute unsigned long long  transferSize;
          readonly attribute unsigned long long  encodedBodySize;
          readonly attribute unsigned long long  decodedBodySize;
          readonly attribute unsigned short responseStatus;
          readonly attribute RenderBlockingStatusType renderBlockingStatus;
          readonly attribute DOMString contentType;
          readonly attribute DOMString contentEncoding;
          [Default] object toJSON();
      };
    </pre>
    <p>
      A {{PerformanceResourceTiming}} has an associated DOMString
      <dfn for="PerformanceResourceTiming">initiator
      type</dfn>.
    </p>
    <p>
      A {{PerformanceResourceTiming}} has an associated DOMString
      <dfn for="PerformanceResourceTiming">delivery
      type</dfn>.
    </p>
    <p>
      A {{PerformanceResourceTiming}} has an associated DOMString
      <dfn for="PerformanceResourceTiming">requested
      URL</dfn>.
    </p>
    <p>
      A {{PerformanceResourceTiming}} has an associated DOMString
      <dfn for="PerformanceResourceTiming">cache mode</dfn>
      (the empty string, "<code>local</code>", or
      "<code>validated</code>").
    </p>
    <p>
      A {{PerformanceResourceTiming}} has an associated [=fetch timing
      info=] <dfn for="PerformanceResourceTiming">timing
      info</dfn>.
    </p>
    <p>
      A {{PerformanceResourceTiming}} has an associated [=response body
      info=] <dfn for="PerformanceResourceTiming">resource
      info</dfn>.
    </p>
    <p>
      A {{PerformanceResourceTiming}} has an associated
      <a href="https://fetch.spec.whatwg.org/#concept-status">status</a>
      <dfn for="PerformanceResourceTiming">response status</dfn>.
    </p>
    <p>
      A {{PerformanceResourceTiming}} has an associated
      {{RenderBlockingStatusType}} <dfn export for=
      "PerformanceResourceTiming">render-blocking status</dfn>.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      When <dfn export>toJSON</dfn> is called, run the [=default toJSON steps=]
      for {{PerformanceResourceTiming}}.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      <dfn export>initiatorType</dfn> getter steps are to return the <a for=
      "PerformanceResourceTiming">initiator type</a> for <a>this</a>.
    </p>
    <div class='note'>
      <p>
        <code>initiatorType</code> returns one of the following values:
      </p>
      <ul>
        <li>
          <code>"navigation"</code>, if the request is a [=navigation
          request=];
        </li>
        <li>
          <code>"body"</code>, if the request is a result of processing the
          <{body}> element's <code>background</code> attribute that's
          already obsolete.
          </li>
          <li>
            <p>
            <code>"css"</code>, if the request is a result of processing a
            CSS <a href="https://www.w3.org/TR/css-values-4/#funcdef-url">url()</a> directive such as <code>@import
                                                                                                                url()</code> or
            <code>background: url()</code>;
            [[CSS-VALUES]]
            </p>
            <p>
              Note: the request for a font resource specified with
              <code>@font-face</code> in CSS is a result of processing a CSS
              directive. Therefore, the <code>initiatorType</code> for this font
              resource is <code>"css"</code>.
            </p>
        </li>
        <li>
          <code>"script"</code>, if the request is a result of loading any
          <a href="https://html.spec.whatwg.org/multipage/webappapis.html#concept-script">script</a> (a classic
          <{script}>, a [=module script=], or a {{Worker}}).
        </li>
        <li>
          <code>"xmlhttprequest"</code>, if the request is a result of
          processing an {{XMLHttpRequest}};
        </li>
        <li>
          <code>"font"</code>, if the request is the result of processing
          fonts. This can happen when fonts request subsequent resources,
          e.g, when Incremental Font Transfer [[INCREMENTAL_FONT_TRANSFER]] is used.
          </li>
          <li>
          <code>"fetch"</code>, if the request is the result of processing
          the {{WindowOrWorkerGlobalScope/fetch()}} method;
        </li>
        <li>
          <code>"beacon"</code>, if the request is the result of processing
          the {{Navigator/sendBeacon()}} method; [[BEACON]]
        </li>
        <li>
          <code>"video"</code>, if the request is the result of processing
          the <{video}> element's <{video/poster}> or <{video/src}>.
        </li>
        <li>
          <code>"audio"</code>, if the request is the result of processing
          the <{audio}> element's <{audio/src}>.
        </li>
        <li>
          <code>"track"</code>, if the request is the result of processing
          the <{track}> element's <{track/src}>.
        </li>
        <li>
          <code>"img"</code>, if the request is the result of processing
          the <{img}> element's <{img/src}> or <{img/srcset}>.
        </li>
        <li>
          <code>"image"</code>, if the request is the result of processing
          the <a href="https://www.w3.org/TR/SVG2/embedded.html#ImageElement">image</a>
          element. [[SVG2]]
        </li>
        <li>
          <code>"input"</code>, if the request is the result of processing
          an <{input}> element of <{input/type}> <a href="https://html.spec.whatwg.org/multipage/input.html#image-button-state-(type=image)">image</a>.
        </li>
        <li>
          <code>"ping"</code>, if the request is the result of processing
          an <{a}> element's <{a/ping}>.
        </li>
        <li>
          <code>"iframe"</code>, if the request is the result of processing
          an <{iframe}>'s <{iframe/src}>.
        </li>
        <li>
          <code>"frame"</code>, if the request is the result of loading a
          <{frame}>.
        </li>
        <li>
          <code>"embed"</code>, if the request is the result of processing
          an <{embed}> element's <{embed/src}>.
          </li>
          <li>
            <code>"link"</code>, if the request is the result of processing
            an <{link}> element.
          </li>
          <li>
            <code>"object"</code>, if the request is the result of processing
            an <{object}> element.
          </li>
          <li>
            <code>"early-hints"</code>, if the request is the result of
            processing an Early Hints [[EARLY_HINTS]] response.
          </li>
          <li>
          <code>"other"</code>, if none of the above conditions match.
        </li>
      </ul>
    </div>
    <p class='note'>
      The setting of <code>initiatorType</code> is done at the different places where
      a resource timing entry is reported, such as the [=fetch=] standard.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      <dfn export>deliveryType</dfn> getter steps are to return the <a for=
      "PerformanceResourceTiming">delivery type</a> for <a>this</a>.
    </p>
    <div class='note'>
      <p>
        <code>deliveryType</code> returns one of the following values:
      </p>
      <ul>
        <li>
          <code>"cache"</code>, if the <a for=
          "PerformanceResourceTiming">cache mode</a> is not the empty
          string.
        </li>
        <li>the empty string <code>""</code>, if none of the above
        conditions match.
        </li>
      </ul>
      <p>
        This is expected to be expanded by future updates to this
        specification, e.g. to describe consuming preloaded resources and
        prefetched navigation requests.
      </p>
    </div>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>workerStart</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/final service worker start time=] and the <a>relevant global
      object</a> for <a>this</a>. See [=/HTTP fetch=] for more info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>redirectStart</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/redirect start time=] and the <a>relevant global object</a> for
      <a>this</a>. See [=/HTTP-redirect fetch=] for more info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>redirectEnd</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/redirect end time=] and the <a>relevant global object</a> for
      <a>this</a>. See [=/HTTP-redirect fetch=] for more info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>fetchStart</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/post-redirect start time=] and the <a>relevant global object</a>
      for <a>this</a>. See [=/HTTP fetch=] for more info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>domainLookupStart</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/final connection timing info=]'s [=connection timing info/domain
      lookup start time=] and the <a>relevant global object</a> for
      <a>this</a>. See <a>Recording connection timing info</a> for more
      info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>domainLookupEnd</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/final connection timing info=]'s [=connection timing info/domain
      lookup end time=] and the <a>relevant global object</a> for
      <a>this</a>. See <a>Recording connection timing info</a> for more
      info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>connectStart</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/final connection timing info=]'s [=connection timing
      info/connection start time=] and the <a>relevant global object</a>
      for <a>this</a>. See <a>Recording connection timing info</a> for more
      info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>connectEnd</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/final connection timing info=]'s [=connection timing
      info/connection end time=] and the <a>relevant global object</a> for
      <a>this</a>. See <a>Recording connection timing info</a> for more
      info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>secureConnectionStart</dfn> getter steps are to <a>convert
      fetch timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/final connection timing info=]'s [=connection timing info/secure
      connection start time=] and the <a>relevant global object</a> for
      <a>this</a>. See <a>Recording connection timing info</a> for more
      info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>nextHopProtocol</dfn> getter steps are to [=/isomorphic
      decode=] <a>this</a>'s [=PerformanceResourceTiming/timing info=]'s
      [=fetch timing info/final connection timing info=]'s [=connection
      timing info/ALPN negotiated protocol=]. See <a>Recording connection
      timing info</a> for more info.
    </p>
    <p class="note">
      Issue <a href=
      "https://github.com/w3c/resource-timing/issues/221">221</a> suggests
      to remove support for nextHopProtocol, as it can reveal details about
      the user's network configuration.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>requestStart</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/final network-request start time=] and the <a>relevant global
      object</a> for <a>this</a>. See [=/HTTP fetch=] for more info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>firstInterimResponseStart</dfn> getter steps are to
      <a>convert fetch timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/first interim network-response start time=] and the <a>relevant
      global object</a> for <a>this</a>. See [=/HTTP fetch=] for more info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>finalResponseHeadersStart</dfn> getter steps are to
      <a>convert fetch timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing
      info/final network-response start time=] and the <a>relevant global
      object</a> for <a>this</a>. See [=/HTTP fetch=] for more info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>responseStart</dfn> getter steps are to return <a>this</a>'s
      {{PerformanceResourceTiming/firstInterimResponseStart}} if it is not
      0; Otherwise <a>this</a>'s
      {{PerformanceResourceTiming/finalResponseHeadersStart}}.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>responseEnd</dfn> getter steps are to <a>convert fetch
      timestamp</a> for <a>this</a>'s <a for=
      "PerformanceResourceTiming">timing info</a>'s [=fetch timing info/end
      time=] and the <a>relevant global object</a> for <a>this</a>. See
      [=/fetch=] for more info.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>encodedBodySize</dfn> getter steps are to return
      <a>this</a>'s <a for="PerformanceResourceTiming">resource
      info</a>'s [=response body info/encoded size=].
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>decodedBodySize</dfn> getter steps are to return
      <a>this</a>'s <a for="PerformanceResourceTiming">resource
      info</a>'s [=response body info/decoded size=].
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>transferSize</dfn> getter steps are:
    </p>
    <ol>
      <li>
        <p>
          If <a>this</a>'s <a for="PerformanceResourceTiming">cache
          mode</a> is "<code>local</code>", then return 0.
        </p>
      </li>
      <li>
        <p>
          If <a>this</a>'s <a for="PerformanceResourceTiming">cache
          mode</a> is "<code>validated</code>", then return 300.
        </p>
      </li>
      <li>
        <p>
          Return <a>this</a>'s <a for=
          "PerformanceResourceTiming">resource info</a>'s [=response
          body info/encoded size=] plus 300.
        </p>
        <p class='note'>
          The constant number added to <code>transferSize</code> replaces exposing the
          total byte size of the HTTP headers, as that might expose the
          presence of certain cookies. See <a href=
          "https://github.com/w3c/resource-timing/issues/238">this
          issue</a>.
        </p>
      </li>
    </ol>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>responseStatus</dfn> getter steps are to return
      <a>this</a>'s <a for="PerformanceResourceTiming">response
      status</a>.
    </p>
    <p class='note'>
      <code>responseStatus</code> is determined in [=Fetch=]. For a cross-origin
      <a href="https://fetch.spec.whatwg.org/#dom-requestmode-no-cors">no-cors</a> request it
      would be 0 because the response would be an <a href=
      "https://fetch.spec.whatwg.org/#concept-filtered-response-opaque">opaque filtered
      response</a>.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>contentType</dfn> getter steps are to return <a>this</a>'s
      <a for="PerformanceResourceTiming">resource info</a>'s
      [=response body info/content type=].
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>contentEncoding</dfn> getter steps are to return
      <a>this</a>'s <a for="PerformanceResourceTiming">resource
        info</a>'s [=response body info/content encoding=].
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>renderBlockingStatus</dfn> getter steps are to return
      <a for="RenderBlockingStatusType">blocking</a> if
      <a>this</a>'s <a for="PerformanceResourceTiming">timing
      info</a>'s [=fetch timing info/render-blocking=] is true; otherwise
      <a for="RenderBlockingStatusType">non-blocking</a>.
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>workerRouterEvaluationStart</dfn> getter steps are to return
      <a>this</a>'s <a for="PerformanceResourceTiming">timing
        info</a>'s [=fetch timing info/service worker timing info=]'s
      [=service worker timing info/worker router evaluation start=].
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>workerCacheLookupStart</dfn> getter steps are to return
      <a>this</a>'s <a for="PerformanceResourceTiming">timing
        info</a>'s [=fetch timing info/service worker timing info=]'s
      [=service worker timing info/worker cache lookup start=].
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>workerMatchedRouterSource</dfn> getter steps are to return
      <a>this</a>'s <a for="PerformanceResourceTiming">timing
        info</a>'s [=fetch timing info/service worker timing info=]'s
      [=service worker timing info/worker matched router source=].
    </p>
    <p dfn-for="PerformanceResourceTiming">
      The <dfn export>workerFinalRouterSource</dfn> getter steps are to return
      <a>this</a>'s <a for="PerformanceResourceTiming">timing
        info</a>'s [=fetch timing info/service worker timing info=]'s
      [=service worker timing info/worker final router source=].
    </p>
    <p class='note'>
      A user agent implementing {{PerformanceResourceTiming}} would need
      to include <code>"resource"</code> in
      {{PerformanceObserver/supportedEntryTypes}}. This allows developers
      to detect support for Resource Timing.
    </p>
    <section>
      <h4 id="sec-render-blocking-status-types">
        RenderBlockingStatusType enum
      </h4>
      <pre class='idl'>
        enum RenderBlockingStatusType {
            "blocking",
            "non-blocking"
        };
      </pre>
      <p>
        The values are defined as follows:
      </p>
      <dl dfn-for='RenderBlockingStatusType'>
        <dt>
          <dfn>blocking</dfn>
        </dt>
        <dd>
          The resource can potentially block rendering.
        </dd>
        <dt>
          <dfn>non-blocking</dfn>
        </dt>
        <dd>
          The resource will not block rendering.
        </dd>
      </dl>
    </section>
  </section>
  <section dfn-for=
  "Performance">
    <h3 id="sec-extensions-performance-interface">
      Extensions to the <code>Performance</code> Interface
    </h3>
    <p>
      The user agent MAY choose to limit how many resources are included as
      {{PerformanceResourceTiming}} objects in the <a>Performance
      Timeline</a> [[PERFORMANCE-TIMELINE-2]]. This section extends the
      <a href="https://www.w3.org/TR/hr-time-3/#dom-performance"><code>Performance</code></a>
      interface to allow controls over the number of
      {{PerformanceResourceTiming}} objects stored.
    </p>
    <p>
      The recommended minimum number of {{PerformanceResourceTiming}}
      objects is 250, though this may be changed by the user agent.
      <a for="Performance">setResourceTimingBufferSize</a> can be
      called to request a change to this limit.
    </p>
    <p>
      Each <a href="https://webidl.spec.whatwg.org/#es-environment">ECMAScript global
      environment</a> has:
    </p>
    <ul>
      <li>A <dfn>resource timing buffer size limit</dfn> which should
      initially be 250 or greater.
      </li>
      <li>A <dfn>resource timing buffer current size</dfn> which is
      initially 0.
      </li>
      <li>A <dfn>resource timing buffer full event pending flag</dfn> which
      is initially false.
      </li>
      <li>A <dfn>resource timing secondary buffer current size</dfn> which
      is initially 0.
      </li>
      <li>A <dfn>resource timing secondary buffer</dfn> to store
      {{PerformanceResourceTiming}} objects that is initially empty.
      </li>
    </ul>
    <pre class="idl">partial interface Performance {
      undefined clearResourceTimings ();
      undefined setResourceTimingBufferSize (unsigned long maxSize);
      attribute EventHandler onresourcetimingbufferfull;
    };
    </pre>
    <p>
      The <dfn export>Performance</dfn> interface is defined in [[HR-TIME]].
    </p>
    <p>
      The method <dfn export>clearResourceTimings</dfn> runs the following steps:
    </p>
    <ol>
      <li>Remove all {{PerformanceResourceTiming}} objects in the
      <a>performance entry buffer</a>.
      </li>
      <li>Set <a>resource timing buffer current size</a> to 0.
      </li>
    </ol>
    <p>
      The <dfn>setResourceTimingBufferSize</dfn> method runs the following
      steps:
    </p>
    <ol>
      <li>Set <a>resource timing buffer size limit</a> to the
      <i>maxSize</i> parameter. If the <i>maxSize</i> parameter is less
      than <a>resource timing buffer current size</a>, no
      {{PerformanceResourceTiming}} objects are to be removed from the
      <a>performance entry buffer</a>.
      </li>
    </ol>
    <p>
      The attribute <dfn export>onresourcetimingbufferfull</dfn> is the event
      handler for the <code>resourcetimingbufferfull</code> event described
      below.
    </p>
    <p>
      To check if <dfn>can add resource timing entry</dfn>, run the
      following steps:
    </p>
    <ol>
      <li>If <a>resource timing buffer current size</a> is smaller than <a>
        resource timing buffer size limit</a>, return true.
      </li>
      <li>Return false.
      </li>
    </ol>

<p>To <dfn>add a PerformanceResourceTiming entry</dfn> <i>new entry</i>
into the <a>performance entry buffer</a>, run the following steps:</p>
<ol>
<li>If <a>can add resource timing entry</a> returns true and
<a>resource timing buffer full event pending flag</a> is false, run
the following substeps:
<ol style="list-style-type: lower-latin;">
<li>Add <i>new entry</i> to the <a>performance entry buffer</a>.</li>
<li>Increase <a>resource timing buffer current size</a> by 1.</li>
<li>Return.</li>
</ol>
</li>
<li>If <a>resource timing buffer full event pending flag</a> is
false, run the following substeps:
<ol style="list-style-type: lower-latin;">
<li>Set <a>resource timing buffer full event pending flag</a> to
true.</li>
<li><a>Queue a task</a> on the <a>performance timeline task source</a> to run <a>fire a buffer full event</a>.</li>
</ol>
</li>
<li>Add <i>new entry</i> to the <a>resource timing secondary
buffer</a>.</li>
<li>Increase <a>resource timing secondary buffer current size</a> by
1.</li>
</ol>
<p>To <dfn>copy secondary buffer</dfn>, run the following steps:</p>
<ol>
<li>While <a>resource timing secondary buffer</a> is not empty and
<a>can add resource timing entry</a> returns true, run the following
substeps:
<ol>
<li>Let <i>entry</i> be the oldest
{{PerformanceResourceTiming}} in <a>resource timing secondary
buffer</a>.</li>
<li>Add <i>entry</i> to the end of <a>performance entry buffer</a>.</li>
<li>Increment <a>resource timing buffer current size</a> by 1.</li>
<li>Remove <i>entry</i> from <a>resource timing secondary buffer</a>.</li>
<li>Decrement <a>resource timing secondary buffer current size</a> by 1.</li>
</ol>
</li>
</ol>
<p>To <dfn>fire a buffer full event</dfn>, run the following steps:</p>
<ol>
<li>While <a>resource timing secondary buffer</a> is not empty, run
the following substeps:
<ol>
<li>Let <i>number of excess entries before</i> be <a>resource
timing secondary buffer current size</a>.</li>
<li>If <a>can add resource timing entry</a> returns false, then
[=fire an event=] named <code>resourcetimingbufferfull</code> at
the {{Performance}} object.</li>
<li>Run <a>copy secondary buffer</a>.</li>
<li>Let <i>number of excess entries after</i> be <a>resource
timing secondary buffer current size</a>.</li>
<li>If <i>number of excess entries before</i> is lower than or
equals <i>number of excess entries after</i>, then remove all
entries from <a>resource timing secondary buffer</a>, set
<a>resource timing secondary buffer current size</a> to 0, and
abort these steps.</li>
</ol>
</li>
<li>Set <a>resource timing buffer full event pending flag</a> to
false.
<p class="note">
This means that if the <code>resourcetimingbufferfull</code>
event handler does not add more room in the buffer than it adds
resources to it, excess entries will be dropped from the buffer.
Developers need to make sure that
<code>resourcetimingbufferfull</code> event handlers call
<code>clearResourceTimings</code> or extend the buffer
sufficiently (by calling
<code>setResourceTimingBufferSize</code>).
</p>
</li>
</ol>
  </section>
  <section>
    <h3 id="sec-cross-origin-resources">
      Cross-origin Resources
    </h3>
    <section class='informative'>
      <h4 id="sec-cross-origin-intro">
        Introduction
      </h4>
      <p>
        As detailed in [=Fetch=], requests for cross-origin resources are
        included as {{PerformanceResourceTiming}} objects in the
        <a>Performance Timeline</a>.
      </p>
      <p>
        If the <a href="https://fetch.spec.whatwg.org/#concept-tao-check">timing
          allow check</a> algorithm fails for a cross-origin resource, the
        entry will be an [=create an opaque timing info|opaque entry=]. Such
        entries have most of their attributes masked in order to prevent
        leaking cross-origin data that isn't otherwise exposed. So, for an
        [=create an opaque timing info|opaque entry=], the following
        attributes will always return zero or the empty string:
        {{PerformanceResourceTiming/redirectStart}},
        {{PerformanceResourceTiming/redirectEnd}},
        {{PerformanceResourceTiming/workerStart}},
        {{PerformanceResourceTiming/domainLookupStart}},
        {{PerformanceResourceTiming/domainLookupEnd}},
        {{PerformanceResourceTiming/connectStart}},
        {{PerformanceResourceTiming/connectEnd}},
        {{PerformanceResourceTiming/requestStart}},
        {{PerformanceResourceTiming/firstInterimResponseStart}},
        {{PerformanceResourceTiming/finalResponseHeadersStart}},
        {{PerformanceResourceTiming/responseStart}},
        {{PerformanceResourceTiming/secureConnectionStart}}, and
        {{PerformanceResourceTiming/nextHopProtocol}}.
      </p>
      <p>
        Some of the properties, like {{PerformanceResourceTiming/contentType}},
        {{PerformanceResourceTiming/encodedBodySize}}, and
        {{PerformanceResourceTiming/decodedBodySize}} are set to zero (or
        the empty string in the case of
        {{PerformanceResourceTiming/contentType}}) when the response is
        <a href="https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-cross-origin">CORS-cross-origin</a>.
      </p>
      <p>
        {{PerformanceResourceTiming/transferSize}} is affected both by the
        <a href="https://fetch.spec.whatwg.org/#concept-tao-check">timing
          allow check</a> and by the
        <a href="https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-cross-origin">CORS-cross-origin</a>
        status.
      </p>
      <p>
        For requests handled by a [=service worker=] using
        {{FetchEvent/respondWith()}}, the reported timing data reflects the
        interaction between the client and the service worker, rather than
        the service worker's own internal network activity. For example, the
        service worker might respond to a same-origin request with a
        cross-origin response or vice versa, or return a cached or synthetic
        response to either. Given that, resources forwarded from a service
        worker do not tell the whole story of fetching the resource, and do
        not go through the <a href="https://fetch.spec.whatwg.org/#concept-tao-check">timing
          allow check</a>. To get the full information about those fetches,
        the service worker's own performance timeline can be inspected.
        [[SERVICE-WORKERS]]
      </p>
      <p>
        For more details, see <a href="https://fetch.spec.whatwg.org/#concept-http-fetch">HTTP Fetch</a>
        #4 - the <a href="https://fetch.spec.whatwg.org/#concept-tao-check">timing
          allow check</a> is only performed when there is no response from the
        service worker. In addition, the [=response=] cloned in the
        {{FetchEvent/respondWith()}} algorithm does not carry the [=/fetch
        timing info=] of the internal fetch, as that information is attached
        to a fetch rather than to a [=response=].
      </p>
    </section>
    <section>
      <h4 id="sec-timing-allow-origin">
        <code>Timing-Allow-Origin</code> Response Header
      </h4>
      <p>
        Server-side applications may return the <a>Timing-Allow-Origin</a>
        HTTP response header to allow the User Agent to fully expose, to the
        document origin(s) specified, the values of attributes that would
        have been zero due to those cross-origin restrictions.
      </p>
      <p>
        The <dfn>Timing-Allow-Origin</dfn> HTTP response header field can
        be used to communicate a policy indicating origin(s) that may be
        allowed to see values of attributes that would have been zero due
        to the cross-origin restrictions. The header's value is represented
        by the following ABNF [[RFC5234]] (using <a href=
        "https://httpwg.org/specs/rfc9110.html#rfc.section.5.6.1">List
        Extension</a>, [[RFC9110]]):
      </p><code class="abnf">Timing-Allow-Origin = 1#( <a href=
      "https://fetch.spec.whatwg.org/#origin-header">origin-or-null</a> / <a href=
      "https://fetch.spec.whatwg.org/#http-new-header-syntax">wildcard</a> )</code>
      <p>
        The sender MAY generate multiple <a>Timing-Allow-Origin</a> header
        fields. The recipient MAY combine multiple
        <a>Timing-Allow-Origin</a> header fields by appending each
        subsequent field value to the combined field value in order,
        separated by a comma.
      </p>
      <p>
        The user agent MAY still enforce cross-origin restrictions and set
        transferSize, encodedBodySize, and decodedBodySize attributes to
        zero, even with Timing-Allow-Origin HTTP response header fields. If
        it does, it MAY also set deliveryType to "".
      </p>
      <p>
        The <a>Timing-Allow-Origin</a> headers are processed in
        <a href="https://fetch.spec.whatwg.org/#tao-check">FETCH</a> to
        compute the attributes accordingly.
      </p>
      <p class="note">
        The Timing-Allow-Origin header might arrive as part of a cached
        response. In case of cache revalidation, according to <a href=
        "https://tools.ietf.org/html/rfc7234#section-4.3.4">RFC 7234</a>,
        the header's value might come from the revalidation response, or if
        not present there, from the original cached resource.
      </p>
      <p class="note">
        Issues <a href=
        "https://github.com/w3c/resource-timing/issues/222">222</a> and
        <a href="https://github.com/w3c/resource-timing/issues/223">223</a>
        suggest to remove wildcard support from Timing-Allow-Origin in
        order to restrict its use.
      </p>
    </section>
    <section>
      <h4 id="sec-iana-considerations">
        IANA Considerations
      </h4>
      <p>
        This section registers <a>Timing-Allow-Origin</a> as a <a href=
        "https://tools.ietf.org/html/rfc3864#section-4.2.2">Provisional
        Message Header</a>.
      </p>
      <dl>
        <dt>
          Header field name:
        </dt>
        <dd>
          <pre class="abnf">Timing-Allow-Origin</pre>
        </dd>
        <dt>
          Applicable protocol:
        </dt>
        <dd>
          http
        </dd>
        <dt>
          Status:
        </dt>
        <dd>
          provisional
        </dd>
        <dt>
          Author/Change controller:
        </dt>
        <dd>
          <a href="https://www.w3.org/">W3C</a>
        </dd>
        <dt>
          Specification document:
        </dt>
        <dd>
          <a href="#sec-timing-allow-origin"></a>
        </dd>
      </dl>
    </section>
  </section>
  <section>
    <h3 id="attribute-descriptions">
      Resource Timing Attributes
    </h3>
    <p>
      This section is non-normative.
    </p>
    <p>
      The following graph illustrates the timing attributes defined by the
      PerformanceResourceTiming interface. Attributes in parenthesis may
      not be available when [=fetch|fetching=] cross-origin resources. User
      agents may perform internal processing in between timings, which
      allow for non-normative intervals between timings.
    </p>
    <figure data-lt='Timing attributes'>
      <figcaption>
        This figure illustrates the timing attributes defined by the
        {{PerformanceResourceTiming}} interface. Attributes in
        parenthesis indicate that they may not be available if the resource
        fails the <a href="https://fetch.spec.whatwg.org/#concept-tao-check">timing allow
        check</a> algorithm.
      </figcaption>
      <!-- Source: https://docs.google.com/document/d/1I7XGNJ57Qgjkg9pL11s7MK7zGEcwAgdNj1W5f7NKbW8/ -->
      <img src="timestamp-diagram.svg" alt="Resource Timing attributes"
      style='margin-top: 1em' width="1000">
    </figure>
  </section>
</section>
<section>
  <h2 id="marking-resource-timing">
    Creating a resource timing entry
  </h2>
  <p>
    To <dfn export>mark resource timing</dfn> given a [=/fetch
    timing info=] |timingInfo|, a DOMString |requestedURL|, a DOMString
    |initiatorType| a <a>global object</a> |global|, a string
    |cacheMode|, a [=/response body info=] |bodyInfo|, a
    <a href="https://fetch.spec.whatwg.org/#concept-status">status</a>
    |responseStatus|, and an optional [=string=] |deliveryType| (by
    default, the empty string), perform the following steps:
  </p>
  <ol>
    <li>Create a {{PerformanceResourceTiming}} object |entry| in
    |global|'s [=global object/realm=].
    </li>
    <li>
      <a>Setup the resource timing entry</a> for |entry|, given
      |initiatorType|, |requestedURL|, |timingInfo|, |cacheMode|,
      |bodyInfo|, |responseStatus|, and |deliveryType|.
    </li>
    <li>
      <a>Queue a PerformanceEntry</a> |entry|.
    </li>
    <li>[=Add a PerformanceResourceTiming entry|Add=] |entry| to
    |global|'s <a>performance entry buffer</a>.
    </li>
  </ol>
  <p>
    To <dfn export>setup the resource timing entry</dfn> for
    {{PerformanceResourceTiming}} |entry| given DOMString
    |initiatorType|, DOMString |requestedURL|, [=/fetch timing info=]
    |timingInfo|, a DOMString |cacheMode|, a [=response body info=]
    |bodyInfo|, a <a href="https://fetch.spec.whatwg.org/#concept-status">status</a>
    |responseStatus|, and an optional DOMString |deliveryType| (by
    default, the empty string), perform the following steps:
  </p>
  <ol>
    <li>Assert that |cacheMode| is the empty string,
    "<code>local</code>", or "<code>validated</code>".
    </li>
    <li>Let |global| be |entry|'s [=relevant global object=].
    </li>
    <li>[=initialize a PerformanceEntry|Initialize=] |entry| given the
    result of <a lt="convert fetch timestamp">converting</a>
    |timingInfo|'s [=fetch timing info/start time=] given |global|,
    "<code>resource</code>", |requestedURL|, and the result of
      <a lt="convert fetch timestamp">converting</a> |timingInfo|'s
      [=fetch timing info/end time=] given |global|.
    </li>
    <li>Set |entry|'s <a for="PerformanceResourceTiming">initiator
    type</a> to |initiatorType|.
    </li>
    <li>Set |entry|'s <a for="PerformanceResourceTiming">requested
    URL</a> to |requestedURL|.
    </li>
    <li>Set |entry|'s <a for="PerformanceResourceTiming">timing
    info</a> to |timingInfo|.
    </li>
    <li>Set |entry|'s <a for="PerformanceResourceTiming">resource
    info</a> to |bodyInfo|.
    </li>
    <li>Set |entry|'s <a for="PerformanceResourceTiming">cache
    mode</a> to |cacheMode|.
    </li>
    <li>Set |entry|'s <a for="PerformanceResourceTiming">response
    status</a> to |responseStatus|.
    </li>
    <li>If |deliveryType| is the empty string and |cacheMode| is not,
    then set |deliveryType| to "<code>cache</code>".
    </li>
    <li>Set |entry|'s <a for="PerformanceResourceTiming">delivery
    type</a> to |deliveryType|.
    </li>
  </ol>
  <p>
    To <dfn>convert fetch timestamp</dfn> given {{DOMHighResTimeStamp}}
    |ts| and <a>global object</a> |global|, do the following:
  </p>
  <ol>
    <li>If |ts| is zero, return zero.
    </li>
    <li>Otherwise, return the [=relative high resolution coarse time=]
    given |ts| and |global|.
    </li>
  </ol>
</section>
<section class='informative'>
  <h2 id="sec-security">
    Security Considerations
  </h2>
  <p>
    The {{PerformanceResourceTiming}} interface exposes timing
    information for a resource to any web page or worker that has
    requested that resource. To limit the access to the
    {{PerformanceResourceTiming}} interface, the
    <a href="https://html.spec.whatwg.org/multipage/browsers.html#same-origin">same origin</a>
    policy is enforced by default and certain attributes are set to zero,
    as described in [=/HTTP fetch=]. Resource providers can explicitly
    allow all timing information to be collected for a resource by adding
    the <a>Timing-Allow-Origin</a> HTTP response header, which specifies
    the domains that are allowed to access the timing information.
  </p>
</section>
<section class='informative'>
  <h2 id="sec-privacy">
    Privacy Considerations
  </h2>
  <p>
    Statistical fingerprinting is a privacy concern where a malicious web
    site might determine whether a user has visited a third-party web site
    by measuring the timing of cache hits and misses of resources in the
    third-party web site. Though the {{PerformanceResourceTiming}}
    interface gives timing information for resources in a document, the
    load event on resources can already measure timing to determine cache
    hits and misses in a limited fashion, and the cross-origin
    restrictions in [=/HTTP Fetch=] prevent the leakage of any additional
    information.
  </p>
</section>
<section class="appendix">
  <h2 id="acknowledgements">
    Acknowledgments
  </h2>
  <p>
    Thanks to Anne Van Kesteren, Annie Sullivan, Arvind Jain, Boris
    Zbarsky, Darin Fisher, Jason Weber, Jonas Sicking, James Simonsen,
    Karen Anderson, Kyle Scholz, Nic Jansma, Philippe Le Hegaret,
    Sigbjørn Vik, Steve Souders, Todd Reifsteck, Tony Gentilcore, William
    Chan, and Alex Christensen for their contributions to this work.
  </p>
</section>
