# .github/workflows/auto-push.yml
name: CI
on:
  pull_request: {}
  push:
    branches: [gh-pages]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          # Replace following with appropriate value. See options.md for details.
          W3C_WG_DECISION_URL: https://w3c.github.io/web-performance/meetings/2021/2021-04-01/index.html
          W3C_BUILD_OVERRIDE: |
             shortName: resource-timing-2
             specStatus: WD
